version: "3.9"
services:
  jupyter-lab:
    container_name: jupyterlab
    image: jupyter/scipy-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work
    env_file: .env
    networks:
      - jupyter
      - elastic
    user: root
networks:
  jupyter:
    name: jupyter
  elastic: # To connect to running elasticsearch container over "elastic" network
    external: true
