version: "3.9"
services:
  jupyter-lab:
    image: jupyter/scipy-notebook:latest
    ports:
      - "10000:8888"
    volumes:
      - ./work:/home/jovyan/work
    env_file: .env
    networks:
      - jupyter

networks:
  jupyter:
    name: jupyter